name: Build and Verify

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for proper git metadata

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm@10.0.0

      - name: Install dependencies
        run: pnpm install

      - name: Build verification package
        working-directory: packages/codinit-dev
        run: pnpm build

      - name: Collect build metadata
        working-directory: packages/codinit-dev
        env:
          OFFICIAL_BUILD: 'true'
          BUILD_SIGNING_SECRET: ${{ secrets.BUILD_SIGNING_SECRET }}
        run: |
          node scripts/collect-metadata.js --output ../../build-metadata.json
          node scripts/collect-metadata.js --embed ../../app/utils/build-info.ts

      - name: Verify build
        working-directory: packages/codinit-dev
        env:
          OFFICIAL_BUILD: 'true'
          BUILD_SIGNING_SECRET: ${{ secrets.BUILD_SIGNING_SECRET }}
        run: node scripts/verify-build.js --mode warn --verbose

      - name: Build main application
        run: pnpm run build

      - name: Upload build metadata
        uses: actions/upload-artifact@v4
        with:
          name: build-metadata
          path: build-metadata.json
          retention-days: 90

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: build/
          retention-days: 30

  verify-strict:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm@10.0.0

      - name: Install dependencies
        run: pnpm install

      - name: Build verification package
        working-directory: packages/codinit-dev
        run: pnpm build

      - name: Strict verification for release
        working-directory: packages/codinit-dev
        env:
          OFFICIAL_BUILD: 'true'
          BUILD_SIGNING_SECRET: ${{ secrets.BUILD_SIGNING_SECRET }}
        run: node scripts/verify-build.js --mode enforce --verbose
